name: Lint

# Run on any push or PR.
on: ["push", "pull_request"]

jobs:
  include-guards:
    name: Header Include Guards

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Checkout submodules (non-recursive)
        submodules: 'true'

    - name: Run header includes guards check
      uses: genoswitch/include-guards-check-action@36c8a9117aecd171e1b187155675f9b4d99f26ff
      with:
        path: "src/"
        pattern: "{last_dir}_{file_base}_H_"