name: Mirror

on: ["push", "delete"]

jobs:
  igem-gitlab:
    name: iGEM GitLab

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all branches and tags

      - name: Mirror repository
        uses: genoswitch/repository-mirroring-action@f0c4a723a841030c3fd86f76241a860edde03015
        with:
          target_repo_url: git@gitlab.igem.org:jcxldn/City-of-London-UK_firmware.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}
